apiVersion: apps/v1
kind: Deployment
metadata:
  name: nevida-ai-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nevida-ai
  template:
    metadata:
      labels:
        app: nevida-ai
    spec:
      containers:
      - name: nevida-ai
        image: your-dockerhub-username/nevida-ai:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: nevida-ai-service
spec:
  selector:
    app: nevida-ai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
